### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by vielmetti** [adityasaky/availability-woes#1]
The story of youtube-dl (a downloader for Youtube videos) is one of alleged
infringing behavior that has impacted availability of the package. This is
exacerbated in part by rapid changes to the Youtube interface, which
has required constant changes to the package.

https://github.com/ytdl-org/youtube-dl 
https://yt-dl.org/

Github blog: https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by adityasaky** [comment]
This is a good example, and I think one that shows this list needs a new section that isn't strictly for dependencies being unavailable!
