### ISSUE TITLE
npm "rc"

### ISSUE THREAD

**Issue by vielmetti** [adityasaky/availability-woes#10]
Similar to the "coa" attack at #9 this involves injecting malware into the system.

https://github.com/dominictarr/rc/issues/131

advisory at https://github.com/advisories/GHSA-g2q5-5433-rhrf notes that the analysis is still in progress, and reads in part:

> The npm package rc had versions published with malicious code. Users of affected versions (1.2.9, 1.3.9, and 2.3.9) should downgrade to 1.2.8 as soon as possible and check their systems for suspicious activity.

> Any computer that has this package installed or running should be considered fully compromised. All secrets and keys stored on that computer should be rotated immediately from a different computer. The package should be removed, but as full control of the computer may have been given to an outside entity, there is no guarantee that removing the package will remove all malicious software resulting from installing it.

**Comment by vielmetti** [comment]
I picked this up from https://twitter.com/ReversingLabs/status/1456363796751175687

**Comment by adityasaky** [comment]
Big day for npm compromises. I imagine pressure is mounting on them to mandate 2fa at the minimum for devs of major packages. rc has over 14 million downloads a week!

**Comment by vielmetti** [comment]
There's a little bit more reporting at https://therecord.media/malware-found-in-coa-and-rc-two-npm-packages-with-23m-weekly-downloads/

> Initially, the coa compromise was spotted first after its new installation routine started crashing build pipelines for React-based applications.

**Comment by adityasaky** [comment]
Added to https://github.com/cncf/tag-security/pull/812/
