### ISSUE TITLE
coa

### ISSUE THREAD

**Issue by vielmetti** [adityasaky/availability-woes#9]
Noted at https://twitter.com/npmjs/status/1456310581846163457

From the advisory:

> The npm package coa had versions published with malicious code. Users of affected versions (2.0.3 and above) should downgrade to 2.0.2 as soon as possible and check their systems for suspicious activity. See this issue for details as they unfold.
> Any computer that has this package installed or running should be considered fully compromised. All secrets and keys stored on that computer should be rotated immediately from a different computer. The package should be removed, but as full control of the computer may have been given to an outside entity, there is no guarantee that removing the package will remove all malicious software resulting from installing it.

This issue https://github.com/veged/coa/issues/99 has the play-by-play

**Comment by vielmetti** [comment]
Bleeping Computer has https://www.bleepingcomputer.com/news/security/popular-coa-npm-library-hijacked-to-steal-user-passwords/

**Comment by vielmetti** [comment]
The analysis from Bleeping Computer suggests that the attack is very similar to what happened to ua-parser-js, #4 .

**Comment by adityasaky** [comment]
I'll submit to the CNCF list. Interesting how much this broke, and how quickly it was detected...

**Comment by adityasaky** [comment]
Thanks, @vielmetti!

**Comment by adityasaky** [comment]
Added to https://github.com/cncf/tag-security/pull/812/
